include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v20.4.0

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "🔖"
  AUTO_DEVOPS_PRODUCTION_AUTO: "🚀"

Install:
  rules:
    - when: never

Lint:
  needs: []
  image: hadolint/hadolint:v1.19.0-debian
  script:
    - hadolint ./Dockerfile

Test:
  rules:
    - when: never

Build:
  rules:
    - when: never

Preprod:
  environment:
    auto_stop_in: 6 months

Register image:
  extends: .autodevops_register_image
  needs: []
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/api
