include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v23.3.0

variables:
  AUTO_DEVOPS_KANIKO: "🐕"
  AUTO_DEVOPS_RELEASE_AUTO: "🔖"
  AUTO_DEVOPS_PRODUCTION_AUTO: "🚀"
  AUTO_DEVOPS_ENABLE_KAPP: "😱"

Install:
  rules:
    - when: never

Lint:
  needs: []
  image: hadolint/hadolint:v2.6.0-debian
  script:
    - hadolint ./Dockerfile

Test:
  rules:
    - when: never

# prevent "Register Kaniko image: needs 'Build'" and "Build: needs 'Install'" messages
Build:
  needs: []
  script:
    - echo "look ma, no build"

Preprod:
  environment:
    auto_stop_in: 6 months
