apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    &a1 {}
  name: cache-sealed-secret
  namespace: serving-ml
spec:
  encryptedData:
    P: AgAWq3uIh91PCrOC00LgXtGwZjMlEEpEKdHJxBm7VXoCbZ3X5TV0rvX6iMe8ff9mQZUbyWDqnPT6lbQhhTpy96T50xOqqaqOjOXIlS6/iUDO3iFjRwOcuRDZMpEUl9EXSZ8apeScocpxUncNfeuRiXSTCY+edmwWCZV08ipf9eVW01I34dV6wfiheX8Cidf1yQeEYYWgqdj7CkYtYS3GqWhTc7dyqyo9udJVY1EG82xZGYMvdBWb7Xv6G7at3fSe0slqBNoB7nlNmv7XquRpZ8IwNgagwdkdryrovawxU9hB0BTmZ1TS0ZQONjotcuOPlLfXgjoqPyu1zg/GLJHxQQI7HLh4CQskTUEcIILA1IQzZ/SmQW/DmVc2qVpC8jQVDY0KvE4/3U57FWSyw038Cy2e+kYqko+uRDhtfgt4WXDrIC1FPkOM7m3ZEEOoiyoRw6f8hqFnHegZm/ikCFTQk45PNd7qJd9m7pLl/rkKYx1MN7JNT5uCblTrIt3fuOtncQz+LIStWl14SyAJsukEeWTtnI2OyEuSPDJmRkYQPTPXD8bFLTb9cdwSkSjTOLsA+R5gdK+KL5kgujZ89vUc0/8USpg8MhKayxnOqtvkvaPrYYCqwTsILBzBJeyOQI4i2x3tjriTy9soWMmIsRezu13Mr4tJWGvb7btPBdDTRKFjSCMgLSTSctzIyLywFy9/E13+bO7iB3DNHQrCqE/DHKuaCgXLs8+CPd7rmPKJvIxO49AE1FErzGO2w1crFNd17pQVW0BZK/sHQNLpO23DjcNk1q9J73TNUrAAx7nVQVYj0A+RHw/vr57q
  template:
    metadata:
      annotations: *a1
      name: cache-sealed-secret
    type: Opaque