apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    &a1 {}
  name: cache-sealed-secret
  namespace: serving-ml
spec:
  encryptedData:
    azurestorageaccountname: AgCVik60mjKsz3pqN2YE14mY/9gbEion+7qhl9L/+kNMQwE6KUtPWYMKAXKseXlA64BQtymtWM4q0Ow/3OcfBps+c/ATaqMyvOFXw6NfGXDvEQ27dRlBkcu3azgz/JDEGJIYuZ8HMnKw1oZGTC89oZ2haAsB3OGcnf9vkfBqD2R7zTCL0xSoNTWTtMVrjVTs8fx0TbDugt9NnTbECJc7WB3Nid8KCmc76x4nHPCQs8RTx353TkgH7YUEkoZxltEqeTuEeY6eBBsSTnTgRibIC0wrgAJqIXqln8T0YuFxZTIfIvh48yFLMoOgM0kXuM15gn7SdND4nr/FMsHAIKFHkrqQFrHPOaBplKIdiIRxl3X3txNrplVrGZDgRVo4FNGS0ciunAm0XpThCAxuD3cW6l0W/ynJwpbFIHMY/6jgRTQQvkTAKUAppJtjX2KV83ue5fSEpaH3WZdllk2/hTRtSsxn33BsB+GYf++FeoHunzXRbnwr2ZONo+Kql1CDvAB3gvL7f/BZgymAhb361M5nO7Y/CbpBtHmktW9RADusKfe6kyZYX4gtmAMrWtC+9cQGFU3G8rCwAstHzcnRJcP7GDWU6bwb5kOr4Ghh+HSiZYNK7MLUUSlTahUkSzW1fzvkZsT8kgpbkTvmudhsvnoHf3pt/TKUOW3P1ksOnNqhJ8Fu3bYfjI7D1t9v/Lt3oF07mN6H/VqrhnpCG/Y+Xw+Z
    azurestorageaccountkey: AgCmk6JmDy2Bn1RTpCxsQCvbAsQGe4gCZ4S8VqbDQZi71V5nHU0r+y7qEn6fdsQ3+m/RFS1/CcjnChJxreGL2wFZ3Ux/eQ1f+G+DMEo482tgelmT8C62ZCIhgz4JqVAdAnlij+JvnhLcOrGhc+zYUPzFtpxRSA8l/w+8GQIvW4ezdK2RrCSGAvj/h82c71i7PEIp1HlMTwAvQhsuornQ/6KNK2WvB3Do0RHid6H7lB64ESNX5f3sSeUXRuJBPahZg+Ppq0u8AcrQg5TB2fgLcY+0uVG/gT86+7peJ6B+7+D7CiV0FavIQ4mPtUx7oBF7wUP2xwHDYA+B3zsSFk6MbdhepA8YYCXMQEXlK153xW5VzVAvQyf/srou6PcznrsI1W7Nd0YbcfC8bUHf+MRONmRIK17pdnCvwAKSXQvEX0jGT6FWB3+S9esqdCDQau4/STPjmMvCfTtTNSJqv41DjIThPHsOycd3wZYPbTAaH7FwRq06IRaiDj3FR4E+/H4LhsA9DqrkdwPLP/U8xufbH2dyQsqR16PJoAnF8MbQ8pBfDf5iD9/amg5Tcc4/PAsRjusaYuHwZfRqQbwVfxCOrKxGPbyynuJkkTiO9UwvgQGttpHt4Yw9fvI3LifOqg2b2Pbh6yTY3nEbg7LYryzoEaLtrZWIsIpuGipAYYLVBgk4HV3+AkiuHcYWsnKUbiEx9HzwXpaDJZLd15XrRdzlPhCaKFqr2oXS7uUQTlUmGPA9MZc/7EHb6k1N8JDH3p025HhNrvBL6WTgJTWq3G+VMkrRs0QZcEZXFsSLsIpWcQ+T8Z+x+sQ66vPC
  template:
    metadata:
      annotations: *a1
      name: cache-sealed-secret
    type: Opaque
