app:
  containerPort: 8501
  probesPath: /v1/models/sentqam
  resources:
    limits:
      cpu: "1"
      memory: 3Gi
    requests:
      cpu: "1"
      memory: 3Gi
  autoscale:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    averageUtilization:
      cpu: 100
      memory: 100
