name: ci
on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      # Don't fast-fail on tag and master
      fail-fast: ${{ github.event_name == 'pull_request' || (github.ref !=
        'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')) }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

      - name: Build
        run: docker build . -t docker.pkg.github.com/socialgouv/serving-ml:${GITHUB_SHA}

      - name: Run
        run: |
          docker run \
            --env MODEL_NAME=sentqam \
            --name serving-ml \
            --publish 8501:8501 \
            --rm \
            docker.pkg.github.com/socialgouv/serving-ml:${GITHUB_SHA} ;

          curl http://localhost:8501/v1/models/sentqam || true;
          curl http://localhost:8501/v1/models/sentqam || true;
          curl http://localhost:8501/v1/models/sentqam || true;
          curl http://localhost:8501/v1/models/sentqam || true;
          curl http://localhost:8501/v1/models/sentqam || true;
          curl http://localhost:8501/v1/models/sentqam || true;
          curl http://localhost:8501/v1/models/sentqam || true;
          curl http://localhost:8501/v1/models/sentqam || true;

      - name: Health
        run: |
          curl http://localhost:8501/v1/models/sentqam;
          while ! curl --output /dev/null --silent --head --fail http://localhost:8501/v1/models/sentqam;
            do sleep 1 && echo -n .;
          done;
          curl http://localhost:8501/v1/models/sentqam;

      - name: Test
        run: |
          curl --request POST --header 'content-type: application/json' --data '{"signature_name":"question_encoder","inputs":["poireau"]}' \
            http://localhost:8501/v1/models/sentqam:predict

      #     curl --request POST \
      #       --url http://localhost:8501/v1/models/sentqam:predict \
      #       --header 'content-type: application/json' \
      #       --data '{"signature_name":"response_encoder","inputs":{"input":["Recettes de plats au poireau"], "context": ["La tarte au poireau. Fondue de poireaux. Poireaux vinaigrette."]}}'

      - name: Stop
        run: |
          docker stop serving-ml
