name: ci
on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      # Don't fast-fail on tag and master
      fail-fast: ${{ github.event_name == 'pull_request' || (github.ref !=
        'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')) }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

      - name: Build
        run: docker build . -t docker.pkg.github.com/socialgouv/serving-ml:${GITHUB_SHA}

      - name: Run
        run: |
          docker run \
            --detach \
            --env MODEL_NAME=sentqam \
            --name serving-ml \
            --publish 8501:8501 \
            --rm \
            docker.pkg.github.com/socialgouv/serving-ml:${GITHUB_SHA}

      - name: Stop
        run: |
          docker stop serving-ml
